management:
  endpoints:
    web:
      exposure:
        include: info,health,camelroutes
  endpoint:
    health:
      enabled: 'true'
    camelroutes:
      read-only: 'true'
      enabled: 'true'
http:
  ssl_data:
    key_store: /Users/dhavalshah/Documents/Finacle/BlockChain/HTTPs-DUMMY-SERVER/newkeys/client-keystore.jks
    trust_store: /Users/dhavalshah/Documents/Finacle/BlockChain/HTTPs-DUMMY-SERVER/newkeys/client-truststore.jks
    key_store_password: prat123
    key_store_type: JKS
    trust_store_password: prat123
    key_alias: java-client
    trust_store_type: JKS
  ssl_enabled: 'true'
  options:
    connectionRequestTimeout: 100
    connectTimeout: 100
    socketTimeout: 100
    maxTotalConnections: 20
    connectionsPerRoute: 20
    #for basic auth
    authUsername: xxxx
    authPassword: yyyy
    authDomain: zzzz
    authHost: aaaa

greeting: Hello World
camel:
  springboot:
    name: MyCamel
  component:
    servlet:
      mapping:
        context-path: /*
timer:
  period: '2000'

utilities1: abc

utilities:
  fbc:
    type: http
    http:
      base_url: 'https://secnodeserver.com:8000'
      ssl_data:
        key_store: /PATH/TO/client-keystore.jks
        trust_store: /PATH/TO/client-truststore.jks
        key_store_password: KeyStorePassword
        key_store_type: JKS
        trust_store_password: TrustStorePassword
        key_alias: java-client
        trust_store_type: JKS
      ssl_enabled: 'true'
      options:
        connectionRequestTimeout: 100
        connectTimeout: 100
        socketTimeout: 100
        maxTotalConnections: 20
        connectionsPerRoute: 20
        #for basic auth
        authUsername: xxxx
        authPassword: yyyy
        authDomain: zzzz
        authHost: aaaa


